name: Python Build and Release

on:
  workflow_dispatch:

jobs:
  Build-Release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up 32-bit Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.8.10'
        architecture: 'x86'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install wxPython

    - name: Build EXE
      run: |
        rm dist -Recurse -Force -ErrorAction Continue
        pyinstaller --onefile -w -i Assets\icon.ico CustomTextDisplayTool.py
        pyinstaller -w -i Assets\icon.ico CustomTextDisplayTool.py
        pyinstaller -w --distpath dist/CustomTextDisplayTool_bsdnsxx -n CustomTextDisplayTool -i Assets\icon.ico CustomTextDisplayTool_bsdnsxx.py

    - name: Package portable EXE
      run: |
        mkdir -p release
        Compress-Archive -Path dist/CustomTextDisplayTool.exe -DestinationPath release/CustomTextDisplayTool_Portable.zip
        echo 'Successfully packaged "CustomTextDisplayTool_Portable".'

    - name: Upload portable EXE to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: CustomTextDisplayTool_Portable
        path: release/CustomTextDisplayTool_Portable.zip

    - name: Upload EXE to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: CustomTextDisplayTool
        path: dist/CustomTextDisplayTool/

    - name: Upload bsdnsxx Customized EXE to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: CustomTextDisplayTool_bsdnsxx
        path: dist/CustomTextDisplayTool_bsdnsxx/CustomTextDisplayTool/

    - name: Move the EXE to the repository
      run: |
        rm "CustomTextDisplayTool/Bin" -Recurse -Force -ErrorAction Continue
        mkdir -p "CustomTextDisplayTool/Bin"
        mv -Path "dist/CustomTextDisplayTool/*" -Destination "CustomTextDisplayTool/Bin/" -Force
        ls CustomTextDisplayTool -Recurse -Force

    - name: Commit and push the EXE to the repository
      run: |
        git add -A
        git commit -m "Add generated EXE files"
        git push origin ${{ github.ref_name }}

    - name: Install NSIS
      run: |
        Start-Process -FilePath 'NSIS\nsis-3.08-setup.exe' -ArgumentList '/S' -NoNewWindow -Wait
        echo 'Installed successfully.'

    - name: Create Installer
      run: |
        Start-Process -FilePath 'C:/Program Files (x86)/NSIS/makensis.exe' -ArgumentList 'NSIS/CustomTextDisplayTool.nsi' -NoNewWindow -Wait
        mv -Path "NSIS/CustomTextDisplayTool_Setup.exe" -Destination "release/" -Force

    - name: Upload Installer to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: CustomTextDisplayTool_Installer
        path: release/CustomTextDisplayTool_Setup.exe

    - name: Temporary move the bsdnsxx Customized EXE to the repository
      run: |
        rm "CustomTextDisplayTool/Bin" -Recurse -Force -ErrorAction Continue
        mkdir -p "CustomTextDisplayTool/Bin"
        mv -Path "dist/CustomTextDisplayTool_bsdnsxx/CustomTextDisplayTool/*" -Destination "CustomTextDisplayTool/Bin/" -Force
        ls CustomTextDisplayTool -Recurse -Force

    - name: Create Installer
      run: |
        Start-Process -FilePath 'C:/Program Files (x86)/NSIS/makensis.exe' -ArgumentList 'NSIS/CustomTextDisplayTool.nsi' -NoNewWindow -Wait

    - name: Upload bsdnsxx Customized Installer to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: CustomTextDisplayTool_bsdnsxx_Installer
        path: NSIS/CustomTextDisplayTool_Setup.exe

    - name: Print files from release dir
      run: ls release -Recurse -Force

    - name: Calculate checksums
      run: pwsh .github/workflows/generate-sha256.ps1 release/

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          release/*.zip
          release/*.exe
        draft: true
        bodyFile: release/checksums.md
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
